### PR TITLE
Corrected YAML

### PR DESCRIPTION
**Pull request by agneevX**
Corrected the YAML code.

### CODE REVIEW

**Comment by maykar** [comment]
May I ask why? It's just an example and even has a warning:

**Do not just copy examples, please use config options above to build your own!**

Also, your example removes the mention of `sensor` which for someone who's never used yaml config might be confused by.

**Comment by agneevX** [comment]
It's an example, but the indenting is not correct. 

> Also, your example removes the mention of sensor which for someone who's never used yaml config might be confused by.

Are you sure? I changed the indentation and the data on some of the examples.

**Comment by maykar** [comment]
Yes, sorry, sensor was kept. The indentation of the current example is valid YAML, just not doubled. While I'm fine changing that I'd rather not have default values represented in the example as they wouldn't be needed.

**Comment by agneevX** [comment]
Is SSL really used in the local subnet, or on the same host?

**Comment by maykar** [comment]
It's just an example to show all options and should never be copy and pasted, especially after being explicitly told not to. If you feel strongly about it, I'll happily change it

**Pull request merged**
