### PR TITLE
Add gitignore from gitignore.io

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Comment by iantrich** [comment]
I don't get it. Why is this needed?

**Comment by halkeye** [comment]
Mostly becaus pycache gets created. I use sub modules to make updating easy and git keeps saying the checkout is dirty.

**Comment by maykar** [comment]
I'm confused as well. Why not do this globally on `/custom_components/`? Otherwise you'd require every custom component project you use to have it's own .gitignore.

**Comment by halkeye** [comment]
Its not a big deal. I can totally do it globally, but you didn't have a git ignore, so i just gave you the default python one from gitignore.io

**Comment by maykar** [comment]
I use a .gitignore for sure, but it does it's job and doesn't need added to the repo. Thanks for putting in the legwork though, I do appreciate it.

**Pull request closed without merging**
