### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by Makhuta**
- issue with missplaced bracked results in not being able to parse api.json()

### CODE REVIEW

**Comment by mkanet** [comment]
Hey @Makhuta (very low-proirity) when you get a chance, maybe you would consider changing the Sonarr Integration's "How many days look ahead for the upcoming sensor" to match the one you have for the Radarr Integration?  This will also give you a chance to spell `upcomming` correctly.  I didnt catch the misspelling either in both cases; even after you told me previously.

image

image

**Comment by Makhuta** [comment]
Sure thing @mkanet, both are done:
the [typo](https://github.com/custom-components/sensor.radarr_upcoming_media/pull/35) in Radarr
and the [typo and feature](https://github.com/custom-components/sensor.sonarr_upcoming_media/pull/39) in Sonarr

**Comment by mkanet** [comment]
Man you're quick!!  I really appreciate it!

**Comment by Makhuta** [comment]
These things I need to done as soon as possible because if I don't I will forget and then they will never be done😂

**Pull request merged**
